# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csample.proto\x12\x05model\"\xf1\x01\n\x06\x41\x63tion\x12\x0e\n\x06player\x18\x01 \x01(\x05\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.model.Action.Type\x12\x19\n\x04\x63\x61rd\x18\x03 \x01(\x0e\x32\x0b.model.Card\x12\x1d\n\x15position_in_draw_pile\x18\x04 \x01(\x05\x12\x1f\n\ncards_seen\x18\x05 \x03(\x0e\x32\x0b.model.Card\"Z\n\x04Type\x12\x0b\n\x07INVALID\x10\x00\x12\r\n\tDRAW_CARD\x10\x01\x12\r\n\tPLAY_CARD\x10\x02\x12\r\n\tGIVE_CARD\x10\x03\x12\x18\n\x14INSERT_EXPLODING_CAT\x10\x04\"D\n\x07InfoSet\x12\x1e\n\x07history\x18\x01 \x03(\x0b\x32\r.model.Action\x12\x19\n\x04hand\x18\x02 \x03(\x0e\x32\x0b.model.Card\"K\n\x06Sample\x12\x0c\n\x04iter\x18\x01 \x01(\x04\x12\x1f\n\x07infoset\x18\x02 \x01(\x0b\x32\x0e.model.InfoSet\x12\x12\n\nadvantages\x18\x03 \x03(\x02*\x9d\x01\n\x04\x43\x61rd\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10\x45XPLODING_KITTEN\x10\x01\x12\n\n\x06\x44\x45\x46USE\x10\x02\x12\x08\n\x04SKIP\x10\x03\x12\x0b\n\x07SLAP_1X\x10\x04\x12\x0b\n\x07SLAP_2X\x10\x05\x12\x12\n\x0eSEE_THE_FUTURE\x10\x06\x12\x0b\n\x07SHUFFLE\x10\x07\x12\x18\n\x14\x44RAW_FROM_THE_BOTTOM\x10\x08\x12\x07\n\x03\x43\x41T\x10\tb\x06proto3')
)

_CARD = _descriptor.EnumDescriptor(
  name='Card',
  full_name='model.Card',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPLODING_KITTEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEFUSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SKIP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAP_1X', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAP_2X', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEE_THE_FUTURE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUFFLE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW_FROM_THE_BOTTOM', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAT', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=415,
  serialized_end=572,
)
_sym_db.RegisterEnumDescriptor(_CARD)

Card = enum_type_wrapper.EnumTypeWrapper(_CARD)
UNKNOWN = 0
EXPLODING_KITTEN = 1
DEFUSE = 2
SKIP = 3
SLAP_1X = 4
SLAP_2X = 5
SEE_THE_FUTURE = 6
SHUFFLE = 7
DRAW_FROM_THE_BOTTOM = 8
CAT = 9


_ACTION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='model.Action.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW_CARD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY_CARD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIVE_CARD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSERT_EXPLODING_CAT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=175,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_ACTION_TYPE)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='model.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='model.Action.player', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='model.Action.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='card', full_name='model.Action.card', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position_in_draw_pile', full_name='model.Action.position_in_draw_pile', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cards_seen', full_name='model.Action.cards_seen', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=265,
)


_INFOSET = _descriptor.Descriptor(
  name='InfoSet',
  full_name='model.InfoSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='history', full_name='model.InfoSet.history', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hand', full_name='model.InfoSet.hand', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=335,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='model.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iter', full_name='model.Sample.iter', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infoset', full_name='model.Sample.infoset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='advantages', full_name='model.Sample.advantages', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=412,
)

_ACTION.fields_by_name['type'].enum_type = _ACTION_TYPE
_ACTION.fields_by_name['card'].enum_type = _CARD
_ACTION.fields_by_name['cards_seen'].enum_type = _CARD
_ACTION_TYPE.containing_type = _ACTION
_INFOSET.fields_by_name['history'].message_type = _ACTION
_INFOSET.fields_by_name['hand'].enum_type = _CARD
_SAMPLE.fields_by_name['infoset'].message_type = _INFOSET
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['InfoSet'] = _INFOSET
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.enum_types_by_name['Card'] = _CARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:model.Action)
  ))
_sym_db.RegisterMessage(Action)

InfoSet = _reflection.GeneratedProtocolMessageType('InfoSet', (_message.Message,), dict(
  DESCRIPTOR = _INFOSET,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:model.InfoSet)
  ))
_sym_db.RegisterMessage(InfoSet)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:model.Sample)
  ))
_sym_db.RegisterMessage(Sample)


# @@protoc_insertion_point(module_scope)
